src/blog/urls.py
from django.urls import path
from .views import HomeView, ArticleDetailView, CategoryView, CategoryDetailView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('article/<slug:slug>', ArticleDetailView.as_view(), name='article-detail'),
    path('categories/', CategoryView.as_view(), name='categories'),
    path('categories/<slug:slug>', CategoryDetailView.as_view(), name='category-detail'),
]

src/core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('members/', include('django.contrib.auth.urls')),
]+ static (settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/blog/models.py
from ckeditor.fields import RichTextField
from colorfield.fields import ColorField
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from datetime import datetime, date


class Category(models.Model):
    class Meta:
        verbose_name_plural = "categories"

    name = models.CharField(max_length=255)
    slug_url = models.SlugField(max_length=50)
    navbar_color = ColorField(default='#343A40')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('home')


class Post(models.Model):
    title = models.CharField(max_length=255)
    slug_url = models.SlugField(max_length=50)
    header_image = models.ImageField(null=True, blank=True, upload_to="header_images/")
    header_img_alt_text = models.CharField(max_length=255, null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    preview = models.CharField(max_length=255)
    body = RichTextField(blank=True, null=True)
    tags = models.CharField(max_length=255)
    post_date = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.title + ' | ' + str(self.author)

    def get_absolute_url(self):
        return reverse('home')

src/blog/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'author', 'preview', 'body', 'slug_url', 'tags', 'category']
        
        help_texts = {
            'preview': '255 chars max',
            'slug_url': "If you don't know what you're doing, leave it as it is",
        }
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Enter the title for your post'})
        self.fields['author'].widget.attrs.update({'class': 'form-control'})
        self.fields['preview'].widget.attrs.update({'class': 'form-control', 'placeholder': 'This will show at the Home Page'})
        self.fields['body'].widget.attrs.update({'class': 'form-control', 'placeholder': 'What is in your mind?'})
        self.fields['tags'].widget.attrs.update({'class': 'form-control','placeholder': 'What is this post related to?'})
        self.fields['category'].widget.attrs.update({'class': 'form-control'})
        self.fields['slug_url'].widget.attrs.update({'class': 'form-control', 'placeholder': 'The post URL'})


class EditForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'preview', 'body', 'tags', 'category']

        help_texts = {
            'preview': '255 chars max',
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Enter the title for your post'})
        self.fields['preview'].widget.attrs.update({'class': 'form-control', 'placeholder': 'This will show at the Home Page'})
        self.fields['body'].widget.attrs.update({'class': 'form-control', 'placeholder': "What's in your mind?"})
        self.fields['tags'].widget.attrs.update({'class': 'form-control','placeholder': 'What is this post related to?'})
        self.fields['category'].widget.attrs.update({'class': 'form-control'})

src/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, View
from .forms import PostForm, EditForm
from .models import Post, Category


def home(request):
    return render(request, 'home.html')


class ArticleDetailView(NavBarView, DetailView):
    model = Post
    
    def get(self, request, slug):
        article = Post.objects.get(slug_url=slug)
        context = {'post': article, 'cat_menu': self.cat_menu}
        return render(request, 'article_details.html', context)


class CategoryView(NavBarView, ListView):
    model = Category
    template_name = 'categories.html'
    ordering = ['id']


class CategoryDetailView(NavBarView, DetailView):
    model = Post
    slug_field = 'slug_url'
    
    def get(self, request, slug):
        category_name = Category.objects.get(slug_url=slug)
        filtered_posts = Post.objects.filter(category=category_name).order_by('-post_date')
        context = {'filtered_posts': filtered_posts,
                   'category_name': category_name,
                   'cat_menu': self.cat_menu}
        return render(request, 'category_detail.html', context)

src/blog/templates/article_details.html
{% extends 'base.html' %}
{% block content %}
<h1>{{ post.title }}</h1>
<small>By: 
{{ post.author.first_name }}
{{ post.author.last_name }} - 
{{ post.post_date }}
{% if user.is_authenticated %}
  {% if perms.blog.change_post %}
    - <a href="{% url 'admin:blog_post_change' post.pk %}">Edit</a>
  {% endif %}
  {% if perms.blog.delete_post %}
    <a href="{% url 'admin:blog_post_delete' post.pk %}">Delete</a></small>
  {% endif %}
{% endif %}  
<hr>
<br/>
{{ post.body|safe }}
<br/><br/>
<div id="disqus_thread"></div>
<script src="{% static 'js/disqusComments.js' %}"></script>
<noscript>Please enable JavaScript to view the <a href="//disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
{% endblock %}

src/blog/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link href="//cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="stylesheet" href="//stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="//cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
    <title>{% block title %} Django Blog | {% if post.title %} {{ post.title }} {% else %} Home {% endif %}{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark" 
    style="background: rgb(2, 0, 36); background: linear-gradient(130deg, rgb(2, 0, 36, 1) 0%,  
    {% if post.category.navbar_color %} {{ post.category.navbar_color }} 
    {% elif category_name.navbar_color %} {{ category_name.navbar_color }}  100% 
    {% else %} #343A40 {% endif %}">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home'%}">Django Blog</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            {% if cat_menu %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown"
                role="button" data-bs-toggle="dropdown" aria-expanded="false">Categories</a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  {% for item in cat_menu %}
                    <li><a class="dropdown-item" href="{% url 'category-detail' item.slug_url %}">{{ item.name }}</a></li>
                  {% endfor %}
                </ul>
              </li>
            {% endif %}
            {% if user.is_authenticated %}
              {% if perms.blog.add_post %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'admin:blog_post_add' %}">Add Post</a>
                </li>
              {% endif %}
              {% if user.is_staff %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'admin:index' %}">Dashboard</a>
                </li>
              {% endif %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Logout</a>
              </li>
            {% endif %}
          </ul>
          <form class="d-flex">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>
    </br>
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="//code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="//stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

src/blog/templates/categories.html
{% extends 'base.html' %}
{% block content %}
<h1>Categories</h1>
<ul>
  {% for category in object_list %}
    <li>
      <strong><a href="{% url 'category-detail' category.slug_url %}">{{ category.name }}</a></strong>
    </li>
  {% endfor %}
</ul>
{% endblock %}

src/blog/templates/category_detail.html
{% extends 'base.html' %}
{% block content %}
<h1>{{ category_name }}</h1>
<br/><hr>
{% for post in filtered_posts %}
  {% if post.header_image %}
    <img src="{{ post.header_image.url }}" 
    {% if post.header_image %} alt="{{ post.header_img_alt_text }}" {% else %} alt="" {% endif %}> 
  {% endif %}
  <a href="{% url 'article-detail' post.slug_url %}"><h3>{{ post.title }}</h3></a>
  <small>By: 
  {{ post.author.first_name }}
  {{ post.author.last_name }} - 
  {{ post.post_date }}
  {% if user.is_authenticated %}
    {% if perms.blog.change_post %}
      - <a href="{% url 'admin:blog_post_change' post.pk %}">Edit</a>
    {% endif %}
    {% if perms.blog.delete_post %}
    <a href="{% url 'admin:blog_post_delete' post.pk %}">Delete</a></small>
    {% endif %}
  {% endif %}
  <br/><br/>
  {{ post.preview }}
  <br/><hr>
  {% empty %}
    <h1>There are no posts in this category</h1>
    <br/>
{% endfor %}
<br/><br/>
<a href="{% url 'categories' %}" class="btn btn-secondary">Back</a>
{% endblock %}

src/blog/templates/home.html
{% extends 'base.html' %}
{% block content %}
<h1>Posts!</h1>
<ul>
  {% for post in object_list %}
    <li>
      {% if post.header_image %}
        <img src="{{ post.header_image.url }}"
        {% if post.header_image %} alt="{{ post.header_img_alt_text }}" {% else %} alt="" {% endif %}> 
      {% endif %}
      <a href="{% url 'article-detail' post.slug_url %}">{{ post.title }}</a> -
      {{ post.author.first_name }}
      {{ post.author.last_name }} -
      {{ post.post_date }}
      {% if user.is_authenticated %}
        {% if perms.blog.change_post %}
          - <small>
          <a href="{% url 'admin:blog_post_change' post.pk %}">Edit</a>
        {% endif %}
        {% if perms.blog.delete_post %}
          <a href="{% url 'admin:blog_post_delete' post.pk %}">Delete</a>
          </small> <br>
        {% endif %}
      {% endif %}
      {{ post.preview }}
    </li>
  {% endfor %}
</ul>
{% endblock %}